import { ComponentMapType } from "../../utils/typedefs/MoviesTVCustomTypes.tsx";
import {
  Birdman,
  Casino,
  GangsofNewYork,
  Goodfellas,
  InglouriousBasterds,
  KillersoftheFlowerMoon,
  NoCountryforOldMen,
  OldBoy,
  Oppenheimer,
  Sicario,
  ASpaceOdyssey,
  TheAviator,
  TheBatman,
  ThereWillBeBlood,
  TrainingDay,
} from "./moviereviews/index.ts";
import {
  BojackHorseman,
  MadMen,
  MindHunter,
  Suits,
} from "./tvreviews/index.ts";

export const ComponentMap: ComponentMapType = {
  Birdman,
  BojackHorseman,
  Casino,
  GangsofNewYork,
  Goodfellas,
  KillersoftheFlowerMoon,
  MadMen,
  MindHunter,
  NoCountryforOldMen,
  OldBoy,
  Oppenheimer,
  Sicario,
  Suits,
  ASpaceOdyssey,
  TheAviator,
  TheBatman,
  ThereWillBeBlood,
  TrainingDay,
  InglouriousBasterds,
};
