import {
  MovieComponentMapType,
  TVComponentMapType,
} from "../../../utils/typedefs/MoviesTVCustomTypes.ts";
import {
  Arrival,
  ASpaceOdyssey,
  Birdman,
  Casino,
  Conclave,
  Cure,
  Dune,
  GangsofNewYork,
  Gladiator,
  Goodfellas,
  InglouriousBasterds,
  KillersoftheFlowerMoon,
  NoCountryforOldMen,
  OldBoy,
  Oppenheimer,
  Pushpa2,
  Sicario,
  TheAviator,
  TheBatman,
  TheSubstance,
  ThereWillBeBlood,
  TrainingDay,
  ThePromisedLand,
  TheTrumanShow,
} from "./moviereviews/index.ts";
import {
  BojackHorseman,
  MadMen,
  MindHunter,
  Suits,
} from "./tvreviews/index.ts";

export const MovieComponentMap: MovieComponentMapType = {
  Arrival,
  Birdman,
  Casino,
  Conclave,
  Cure,
  Dune,
  GangsofNewYork,
  Gladiator,
  Goodfellas,
  KillersoftheFlowerMoon,
  NoCountryforOldMen,
  OldBoy,
  Oppenheimer,
  Pushpa2,
  Sicario,
  ASpaceOdyssey,
  TheAviator,
  TheBatman,
  TheSubstance,
  TheTrumanShow,
  ThereWillBeBlood,
  TrainingDay,
  InglouriousBasterds,
  ThePromisedLand,
};

export const TVComponentMap: TVComponentMapType = {
  BojackHorseman,
  MadMen,
  MindHunter,
  Suits,
};
