import {
  BalancedBinaryTree,
  BestTimeToBuyAndSellStock,
  CombinationSum,
  CountingBits,
  InsertInterval,
  LinkedListCycle,
  LongestCommonPrefix,
  MajorityElement,
  MaximumSubarray,
  MergeTwoSortedLists,
  MissingNumber,
  ProductOfArrayExceptSelf,
  ReverseLinkedList,
  RottingOranges,
  SearchRotatedSortedArray,
  ThreeSum,
  TwoSum,
} from "./problems/index.ts";

import { ProblemComponentMapType } from "../../../utils/typedefs/LearningsCustomTypes.ts";

export const ProblemComponentMap: ProblemComponentMapType = {
  BalancedBinaryTree,
  BestTimeToBuyAndSellStock,
  CombinationSum,
  CountingBits,
  InsertInterval,
  LinkedListCycle,
  LongestCommonPrefix,
  MajorityElement,
  MaximumSubarray,
  MergeTwoSortedLists,
  MissingNumber,
  ProductOfArrayExceptSelf,
  ReverseLinkedList,
  RottingOranges,
  SearchRotatedSortedArray,
  ThreeSum,
  TwoSum,
};
